SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE rental_info;
TRUNCATE TABLE app_user;
TRUNCATE TABLE video;
TRUNCATE TABLE video_type;

TRUNCATE TABLE rental_info RESTART IDENTITY;
TRUNCATE TABLE app_user RESTART IDENTITY;
TRUNCATE TABLE video RESTART IDENTITY;
TRUNCATE TABLE video_type RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;